FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN addgroup -S athluna && adduser -S athluna -G athluna
COPY app.jar app.jar
RUN chown -R athluna:athluna /app
USER athluna
ENV JAVA_OPTS="-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/heapdump.hprof"
ENV SPRING_PROFILES_ACTIVE=prod
EXPOSE 8082
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
